---
title: "reformatting-ny-data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{reformatting-ny-data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(precinctsopenelex)
```

First we'll run the default sample function to make sure it works.
```{r}
hello()

```

Now let's get to the NY processing

```{r}

library(dplyr)
library(tidyr)
library(stringr)
library(janitor)
library(readxl)

### We'll create a function to handle the repetitive part of the processing
# once the initial excel cleanup steps are taken. The file will have a precinct column,
# followed by columns with vote results with names formatted as "candidate - party"
# Function wants:
# - office: text label for office (e.g. "U.S. House")
# - district: text label for district (e.g. "42")
                                 
process_ny_data <- function(df, office, district){
  #determine how many columns, since races can have diff number of candidates
  colnum <- length(colnames(df))  
  #begin processing dataset
  df <- df %>% 
    #transform to long/tidy format
    pivot_longer(cols = 2:all_of(colnum), names_to = "name", values_to = "votes") %>% 
    #clean and add necessary columns
    mutate(
      temp = str_split(name, " - ", simplify = TRUE),
      candidate = temp[, 1],
      party = temp[, 2],
      office = office,
      district = district,
      candidate = str_replace_all(candidate, "WriteIn", "Write-Ins") #standarize with openelex name
    ) %>%
    #reorder columns to match openelex format
    select(
      precinct, office, district, candidate, party, votes
    ) 
  #return results
  return(df)
}



#create county name variable to add correct county to the data you're processing
target_county <- "Saratoga"


# Presidential ####
#run processing function sourced at the top along with import in one step
# Function wants:
# - dataset (or import from excel function)
# - office: text label for office (e.g. "U.S. House")
# - district: text label for district (e.g. "42")

# *note: the import function itself can be wrapped inside, as long as the data coming in is the correct structure
# processed_prez <- process_ny_data(read_excel(filestring_import, sheet = "presidential"), 
#                                   "President", 
#                                   "")

#we'll use the included sample dataset - "precinctsampledata_ny" - to demonstrate that's been cleaned and ready for processing
head(precinctsampledata_ny)
glimpse(precinctsampledata_ny)
#note the precise way of formatting the column names that will allow the function to work correctly:
# -candidate columns should be written as "candidate name - party"
# -additional choices should be listed as "WriteIn" (write-in votes), "Blanks" (undervotes), and "Voids" (overvotes)


#now let's run the processing to reformat the data into the open elections standardized format, which is tidy/long
#as opposed to wide

# Function wants:
# - dataset (or import from excel function)
# - office: text label for office (e.g. "U.S. House")
# - district: text label for district (e.g. "42"; note that presidential has no district, it's just "")

processed_prez <- process_ny_data(precinctsampledata_ny,
                                  "Presidential",
                                  "")

head(processed_prez, 10)




```


